import './globals.css'
import { Inter } from 'next/font/google'
//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";
// import "primereact/resources/themes/tailwind-light/theme.css "    
    
//core
import "primereact/resources/primereact.min.css"; 
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>{children}</body>
      </Providers>
        
      
    </html>
  )
}
