account:
  avatar:
    width: 150
    height: 150
fileLocation: /app/pkg/webui/dist/static/logs/admin
maxSize: 4000000
compress: false
maxAge: 35
enableConsole: true
enableFile: true
base:
  # baseurl: http://sahadi.dev.axiomwallet.com:8081/
  isenableaccess: false
  isenablecode: false
  logpath: /data/log
  # port: 8081
  sitename: AMSTECH User Authentication
  # apiurl: http://sahadi.dev.axiomwallet.com:8082/rpc
casbin:
  model:
    rule_0: config/casbin/rbac_model_0.conf
cors:
  allow_credentials: true
  allow_headers:
  - '*'
  allow_methods:
  - GET
  - POST
  - OPTIONS
  - PUT
  - DELETE
  allow_origins:
  - '*'
  enable: true
  max_age: 7200
database:
  driver: mysql
  mysql:
#   mysql -h 192.168.200.2 -u ahadi -p
# Password is "Axiom099#"
    charset: utf8
    host: ${APP_MYSQLHOST}:${APP_MYSQLPORT}
    name: zeus
    password: ${APP_MYSQLPASS}
    pool:
      max: 20
      min: 5
    ssl: false
    user: ${APP_MYSQLUSERNAME}
  sqlite:
    dsn: data/zeus.db
dingtalk:
  agentid: 310135985
  appkey: dingvgvn9hdcp8qtarno
  appsecret: Sn887TtSQgGQNRcSaP-cNQXKYOkuT062vPgHoVvbTm5-HA2qnyew6xbdgZwhxD8N
  cachepath: data/
  corpid: dingd60a58f4e3be699235c2f4657eb6378f
  snsappid: dingoa1uudyxl2dcjvqpij
  snssecret: o8YvDT5l2zb9dikuCbz0HXOiOaVwdyVResrDVyFaqojv0EwZp8ygAemFyoSBh_lz
  ssosecret: XU3oARxOHw731w4LYEJodPEPtppX5oMa7XPp5dv2VjTLak9I--glTDBLLbcl2VpQ
domain: bullteam.local
email:
  smtp:
    address: ss@163.com
    password: xxxxxx
    port: 25
    server: smtp.163.com
    user: vcoso@163.com
jwt:
  expiresat: 3600*24*1
  key:
    private: keys/jwt_private_key.pem
    public: keys/jwt_public_key.pem
lang:
  names: English
  types: en-US
ldap:
  addr: 127.0.0.1:389
  attributes:
  - cn
  - displayName
  - mail
  authfilter: (&(uid=%s))
  basedn: dc=bullteam,dc=com
  binddn: cn=admin,dc=bullteam,dc=com
  bindpass: zeus@admin#123456
  starttls: false
  tls: false
  userdn: cn=admin,dc=bullteam,dc=com
mode: debug
project:
  merge: true
redis:
  host: ${APP_REDIS_HOST}
  auth:
  db: 0
  pool:
    max: 20
    min: 3
security:
  install_lock: false
  2fa:
    enabled: false
  #0 - normal
  #1 - safe
  # check if user has been not doing anything in 1 hour then sign out automatically
  # force user to change password in 90 days
  level: 0
